### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by pchaganti** [twonegatives/attentive_sidekiq#2]
Looking for some clarification on the behavior of Attentive. Seeing this issue with SK as far as jobs once in a while just silently disappearing. Sometimes when a job is marked as disappeared by Attentive, checking for that JID through SK API, SK still has that JID and thinks it is processing the job? 

```
Sidekiq::Queue.new.find_job(j["jid"])
```

thanks!

**Comment by twonegatives** [comment]
Hi, @pchaganti, and thanks for trying out attentive_sidekiq!

We mark jobs as disappeared as far as they have not been finished properly (with the calling of a whole middleware chain) and not present in any worker's current payload.

First thing which comes to my mind of how the described situation can be possible as that Sidekiq itself simply has not removed the disappeared job from the queue yet. In this case, rechecking that JID in a couple of minutes should give the desired result (absence of that job).

Another one is a bit more complex. Due to the way Sidekiq terminates its workers, it is theoretically possible that jobs are returned to redis, but middleware chain is not finished properly. In this case Attentive Sidekiq has nothing to do but to warn you of a disappeared job, which has to be rechecked manually. In case of a false positive, there is an option to delete a job from disappeared list both using UI or API.

**Comment by pchaganti** [comment]
Awesome. Thx for the clarification!
